version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: challenge_tempo_postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: julianvega03/challenge-tempo:latest
    container_name: challenge_tempo_app
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
