server.port=8080

spring.application.name=tenpo-challenge
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/tenpo_db
spring.datasource.username=${DB_USER:tenpo}
spring.datasource.password=${DB_PASSWORD:tenpo123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.threads.virtual.enabled=true

cors.allowed-origins=http://localhost:4200,http://localhost:8080
external.percentage.url=http://localhost:${server.port}/mock/percentage
external.percentage.connect-timeout=2000
external.percentage.read-timeout=3000

retry.max-attempts=3
retry.backoff-delay=300

logging.level.com.challenge.challengetenpo=DEBUG
logging.level.org.springframework.retry=DEBUG
